package com.witte.lozify.data.repository

import android.content.Context
import android.net.Uri
import com.witte.lozify.core.common.ImageUtils
import com.witte.lozify.core.preferences.UserPreferencesManager
import com.witte.lozify.data.local.dao.AttachmentDao
import com.witte.lozify.data.mapper.toDomainModel
import com.witte.lozify.data.mapper.toDomainModels
import com.witte.lozify.data.mapper.toEntity
import com.witte.lozify.domain.model.Attachment
import com.witte.lozify.domain.repository.AttachmentRepository
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.time.Instant
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Implementation of AttachmentRepository interface.
 *
 * Stage 6: Handles image attachment operations with privatization.
 * Stage 37: Dynamic image compression based on UserPreferencesManager.
 *
 * Key Responsibilities:
 * - Copy images from external storage to app private directory (with optional 2K compression)
 * - Manage attachment metadata in Room database
 * - Clean up orphaned image files
 *
 * @property attachmentDao DAO for attachment operations
 * @property preferencesManager User preferences manager
 * @property context Application context for file operations
 */
@Singleton
class AttachmentRepositoryImpl @Inject constructor(
    private val attachmentDao: AttachmentDao,
    private val preferencesManager: UserPreferencesManager,
    @ApplicationContext private val context: Context
) : AttachmentRepository {

    override fun getAttachmentsForNote(noteId: Long): Flow<List<Attachment>> {
        return attachmentDao.getAttachmentsForNote(noteId).map { it.toDomainModels() }
    }

    override suspend fun insertAttachment(attachment: Attachment): Long {
        return attachmentDao.insertAttachment(attachment.toEntity())
    }

    override suspend fun deleteAttachment(attachmentId: Long) {
        // Get attachment to retrieve file path before deletion
        val attachment = attachmentDao.getAttachmentById(attachmentId)
        attachment?.let {
            // Delete physical file from private storage
            val uri = Uri.parse("file://${context.filesDir}/${it.filePath}")
            ImageUtils.deleteImage(context, uri)

            // Delete database record
            attachmentDao.deleteAttachment(it)
        }
    }

    override suspend fun addImageAttachment(noteId: Long, sourceUri: Uri): Attachment? {
        return try {
            // Copy image to private storage with compression toggle
            val isCompressionEnabled = preferencesManager.imageCompressionEnabled.value
            val privateUri = ImageUtils.copyImageToPrivateStorage(
                context = context,
                sourceUri = sourceUri,
                enableCompression = isCompressionEnabled
            ) ?: return null

            // Extract relative file path from private URI
            val filePath = privateUri.path?.removePrefix(context.filesDir.absolutePath + "/") ?: return null

            // Create attachment metadata
            val attachment = Attachment(
                id = 0, // Auto-generated by Room
                noteId = noteId,
                filePath = filePath,
                displayOrder = 0, // Will be updated by caller if needed
                createdAt = Instant.now()
            )

            // Insert to database
            val attachmentId = attachmentDao.insertAttachment(attachment.toEntity())

            attachment.copy(id = attachmentId)
        } catch (e: Exception) {
            // Stage 6 Fix: Catch all exceptions to prevent crash
            e.printStackTrace()
            null
        }
    }

    override suspend fun cleanupOrphanedImages() {
        // Get all attachment file paths currently in database
        val allAttachments = attachmentDao.getAllAttachments()
        val referencedPaths = allAttachments.map { it.filePath }

        // Clean up files not referenced in database
        val deletedCount = ImageUtils.cleanupOrphanedImages(context, referencedPaths)
        // Log or report cleanup result if needed
    }
}
