package com.witte.lozify.presentation.editor

import android.net.Uri
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.witte.lozify.core.common.TagUtils
import com.witte.lozify.domain.model.Note
import com.witte.lozify.domain.model.Tag
import com.witte.lozify.domain.repository.AttachmentRepository
import com.witte.lozify.domain.repository.NoteRepository
import com.witte.lozify.domain.repository.TagRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import java.time.Instant
import javax.inject.Inject

/**
 * ViewModel for note editor.
 *
 * Handles note creation and saving to Room database.
 * Uses SharedFlow to emit one-time events like save success.
 *
 * Stage 4: Integrated automatic #tag extraction and database persistence.
 * Stage 6: Integrated image attachment handling with AttachmentRepository.
 */
@HiltViewModel
class EditorViewModel @Inject constructor(
    private val noteRepository: NoteRepository,
    private val tagRepository: TagRepository,
    private val attachmentRepository: AttachmentRepository
) : ViewModel() {

    /**
     * Events emitted by the editor.
     */
    sealed class EditorEvent {
        data class NoteSaved(val noteId: Long, val tagCount: Int) : EditorEvent()
        data class SaveError(val message: String) : EditorEvent()
    }

    private val _events = MutableSharedFlow<EditorEvent>()
    val events: SharedFlow<EditorEvent> = _events.asSharedFlow()

    /**
     * Save a new note to the database with automatic tag extraction.
     *
     * Stage 4: Extracts all #tags from content, creates/links them to note.
     * Stage 5: Added noteId parameter for updating existing notes.
     * Stage 6: Added imageUris parameter for image attachment handling.
     *
     * @param content The note content text
     * @param imageUris List of selected image URIs to attach
     * @param noteId Optional note ID for editing (null for new note)
     */
    fun saveNote(content: String, imageUris: List<Uri> = emptyList(), noteId: Long? = null) {
        if (content.isBlank()) {
            return
        }

        viewModelScope.launch {
            try {
                val now = Instant.now()

                // Extract tags from content using TagUtils
                val tagNames = TagUtils.extractTags(content)

                // Get or create Tag entities for each extracted tag
                val tags = tagNames.map { tagName ->
                    val tagId = tagRepository.getOrCreateTag(tagName)
                    Tag(
                        id = tagId,
                        name = tagName,
                        createdAt = now,
                        usageCount = 0 // Will be incremented by repository
                    )
                }

                if (noteId != null) {
                    // Stage 5: Update existing note
                    val existingNote = noteRepository.getNoteById(noteId).first()
                    existingNote?.let { note ->
                        val updatedNote = note.copy(
                            content = content.trim(),
                            updatedAt = now,
                            tags = tags
                        )
                        noteRepository.updateNote(updatedNote)
                        _events.emit(EditorEvent.NoteSaved(noteId, tags.size))
                    }
                } else {
                    // Create new note
                    val note = Note(
                        id = 0, // Auto-generated by Room
                        content = content.trim(),
                        createdAt = now,
                        updatedAt = now,
                        isPinned = false,
                        isDeleted = false,
                        tags = tags, // Stage 4: Now includes extracted tags
                        attachments = emptyList(),
                        outgoingRelations = emptyList(),
                        incomingRelations = emptyList()
                    )

                    val newNoteId = noteRepository.insertNote(note)

                    // Stage 6: Process image attachments with error handling
                    imageUris.forEach { uri ->
                        try {
                            attachmentRepository.addImageAttachment(newNoteId, uri)
                        } catch (e: Exception) {
                            // Continue processing other images even if one fails
                            e.printStackTrace()
                        }
                    }

                    _events.emit(EditorEvent.NoteSaved(newNoteId, tags.size))
                }
            } catch (e: Exception) {
                _events.emit(EditorEvent.SaveError(e.message ?: "保存失败"))
            }
        }
    }
}
