package com.witte.lozify.presentation.editor

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.witte.lozify.domain.model.Note
import com.witte.lozify.domain.repository.NoteRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.launch
import java.time.Instant
import javax.inject.Inject

/**
 * ViewModel for note editor.
 *
 * Handles note creation and saving to Room database.
 * Uses SharedFlow to emit one-time events like save success.
 */
@HiltViewModel
class EditorViewModel @Inject constructor(
    private val noteRepository: NoteRepository
) : ViewModel() {

    /**
     * Events emitted by the editor.
     */
    sealed class EditorEvent {
        data class NoteSaved(val noteId: Long) : EditorEvent()
        data class SaveError(val message: String) : EditorEvent()
    }

    private val _events = MutableSharedFlow<EditorEvent>()
    val events: SharedFlow<EditorEvent> = _events.asSharedFlow()

    /**
     * Save a new note to the database.
     *
     * @param content The note content text
     */
    fun saveNote(content: String) {
        if (content.isBlank()) {
            return
        }

        viewModelScope.launch {
            try {
                val now = Instant.now()
                val note = Note(
                    id = 0, // Auto-generated by Room
                    content = content.trim(),
                    createdAt = now,
                    updatedAt = now,
                    isPinned = false,
                    isDeleted = false,
                    tags = emptyList(),
                    attachments = emptyList(),
                    outgoingRelations = emptyList(),
                    incomingRelations = emptyList()
                )

                val noteId = noteRepository.insertNote(note)
                _events.emit(EditorEvent.NoteSaved(noteId))
            } catch (e: Exception) {
                _events.emit(EditorEvent.SaveError(e.message ?: "保存失败"))
            }
        }
    }
}
